Traceback (most recent call last):
  File "C:\Users\CLF\AppData\Roaming\uv\python\cpython-3.13.3-windows-x86_64-none\Lib\multiprocessing\shared_memory.py", line 189, in __del__
    self.close()
  File "C:\Users\CLF\AppData\Roaming\uv\python\cpython-3.13.3-windows-x86_64-none\Lib\multiprocessing\shared_memory.py", line 232, in close
    self._mmap.close()
BufferError: cannot close exported pointers exist
Exception ignored in: <function SharedMemory.__del__ at 0x000001B841CAB060>
Traceback (most recent call last):
  File "C:\Users\CLF\AppData\Roaming\uv\python\cpython-3.13.3-windows-x86_64-none\Lib\multiprocessing\shared_memory.py", line 189, in __del__
    self.close()
  File "C:\Users\CLF\AppData\Roaming\uv\python\cpython-3.13.3-windows-x86_64-none\Lib\multiprocessing\shared_memory.py", line 232, in close
    self._mmap.close()
BufferError: cannot close exported pointers exist
Exception ignored in: <function SharedMemory.__del__ at 0x000001B841CAB060>
Traceback (most recent call last):
  File "C:\Users\CLF\AppData\Roaming\uv\python\cpython-3.13.3-windows-x86_64-none\Lib\multiprocessing\shared_memory.py", line 189, in __del__
    self.close()
  File "C:\Users\CLF\AppData\Roaming\uv\python\cpython-3.13.3-windows-x86_64-none\Lib\multiprocessing\shared_memory.py", line 232, in close
    self._mmap.close()
BufferError: cannot close exported pointers exist
